//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartHomeLocal.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.ReturnLogs = new HashSet<ReturnLog>();
        }
    
        public int Id { get; set; }
        public int ActionId { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> RepeatTimeMinutes { get; set; }
        public Nullable<int> RepeatTimeSeconds { get; set; }
        public bool IsSensor { get; set; }
    
        public virtual Action Action { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReturnLog> ReturnLogs { get; set; }
    }
}
