CREATE DATABASE [SmartHomeMainDb]
GO

USE [SmartHomeMainDb]
GO

CREATE TABLE [User] (
    Id			int			IDENTITY(1,1) PRIMARY KEY,
    Username	nvarchar(255)	NOT NULL,
    Password	nvarchar(255)	NOT NULL,
    Role		nvarchar(255)	NOT NULL,
    Mail		nvarchar(255)	NOT NULL,
	Phone		nvarchar(255)	NOT NULL
);

CREATE TABLE [State] (
    Id			int				IDENTITY(1,1) PRIMARY KEY,
    Name		nvarchar(255)	NOT NULL,
    Abbrevation	nvarchar(255)	NOT NULL
);

CREATE TABLE [City] (
    Id			int			IDENTITY(1,1) PRIMARY KEY,
    Name		nvarchar	NOT NULL,
    CoordX		float		NOT NULL,
    CoordY		float		NOT NULL,
	StateId		int,
	FOREIGN KEY (StateId) REFERENCES [State](Id)
);

CREATE TABLE [House] (
    Id			int			IDENTITY(1,1) PRIMARY KEY,
    Ip			nvarchar(255)	NOT NULL,
    Port		nvarchar(255)	NOT NULL,
    DbName		nvarchar(255)	NOT NULL,
	Name		nvarchar(255)	NOT NULL,
	Address		nvarchar(255)	NOT NULL,
	Contact		nvarchar(255)	NOT NULL,
    UserId		int			NOT NULL,
	CityId		int			NOT NULL,
	StateId		int			NOT NULL,
	FOREIGN KEY (UserId) REFERENCES [User](Id),
	FOREIGN KEY (CityId) REFERENCES [City](Id),
	FOREIGN KEY (StateId) REFERENCES [State](Id)
);

INSERT INTO [State] (Name, Abbrevation) VALUES
	('Afrikaans', 'AI'),
	('Algeria', 'AL'),
	('Angola', 'AN'),
	('Bantu', 'BA'),
	('Benin', 'BE'),
	('Botswana', 'BT'),
	('Burkina Faso (Upper Volta)', 'BF'),
	('Burundi', 'BR'),
	('Bushman', 'BU'),
	('Bushongo', 'BH'),
	('Cameroon', 'CR'),
	('Canary Is.', 'CI'),
	('Cape Verde', 'CV'),
	('Central African Republic', 'CA'),
	('Dahomean', 'DH'),
	('Democratic Republic of the Congo', 'DC'),
	('Egypt', 'EG'),
	('Eritrea', 'ER'),
	('Ethiopia', 'ET'),
	('Gabon', 'GB'),
	('Gambia', 'GA'),
	('Ghana', 'GH'),
	('Gold Coast', 'GC'),
	('Guinea', 'GU'),
	('Hottentot', 'HO'),
	('Ivory Coast', 'IC'),
	('Kenya', 'KY'),
	('Lesotho', 'LE'),
	('Liberia', 'LI'),
	('Libya', 'LB'),
	('Madagascar', 'MD'),
	('Malawi', 'MW'),
	('Mali', 'ML'),
	('Mande', 'MN'),
	('Mauritania', 'MU'),
	('Mauritius', 'MA'),
	('Mbundu', 'MB'),
	('Mende', 'ME'),
	('Morocco', 'MR'),
	('Mozambique', 'MZ'),
	('Namibia', 'NM'),
	('Niger', 'NG'),
	('Nigeria', 'NI'),
	('Pygmy', 'PY'),
	('Republic of Chad', 'CH'),
	('Republic of Djibouti', 'RD'),
	('Republic of Equatorial Guinea', 'RE'),
	('Republic of Guinea-Bissau', 'RG'),
	('Republic of Sao Tome and Principe', 'RS'),
	('Republic of Seychelles', 'SY'),
	('Republic of the Congo (Congo-Brazzaville)', 'RC'),
	('Reunion Island', 'RI'),
	('Rwanda', 'RW'),
	('Semitic', 'SE'),
	('Senegal', 'SN'),
	('Sierra Leone', 'SL'),
	('Somalia', 'SO'),
	('South Africa', 'SA'),
	('South Sudan', 'SS'),
	('Sudan', 'SU'),
	('Swahili', 'SH'),
	('Swaziland', 'SW'),
	('Tanzania', 'TA'),
	('Togo', 'TO'),
	('Tunisia', 'TN'),
	('Uganda', 'UG'),
	('Union of the Comoros', 'UC'),
	('Yao', 'YA'),
	('Zaire', 'ZA'),
	('Zambia', 'ZM'),
	('Zimbabwe', 'ZI'),
	('Zulu', 'ZU'),
	('America (Antarctica)', 'AM'),
	('France (Antarctica)', 'FR'),
	('New Zealand (Antarctica)', 'NZ'),
	('Abkhazian', 'AH'),
	('Afghanistan', 'AF'),
	('Akkadian (Accadian)', 'AK'),
	('Altai', 'AL'),
	('Arabian', 'AR'),
	('Armenian', 'AM'),
	('Assyrian', 'AY'),
	('Assyro-Babylonian', 'AB'),
	('Azerbaijan', 'AZ'),
	('Babylon', 'BY'),
	('Bahrain', 'BI'),
	('Bangladesh', 'BA'),
	('Bengal', 'BE'),
	('Bhutan', 'BH'),
	('Borneo', 'BO'),
	('Brunei', 'BN'),
	('Buriat', 'BR'),
	('Burma', 'BU'),
	('Cambodia', 'CM'),
	('China', 'CH'),
	('Chukchi', 'CU'),
	('Democratic Peoples Republic of Korea', 'DK'),
	('Elamite', 'EL'),
	('Evenki', 'EV'),
	('Georgia', 'GE'),
	('Hattic', 'HA'),
	('Hebrew', 'HE'),
	('Hindu', 'HI'),
	('Hittite', 'HT'),
	('India', 'IN'),
	('Indonesia', 'ID'),
	('Iran', 'IR'),
	('Iraq', 'IQ'),
	('Israel', 'IS'),
	('Itelmen', 'IT'),
	('Japan', 'JA'),
	('Jewish', 'JW'),
	('Jordan', 'JO'),
	('Kashmir', 'KA'),
	('Kazakhstan', 'KZ'),
	('Ket', 'KT'),
	('Korea', 'KR'),
	('Kuwait', 'KU'),
	('Kyrgyzstan', 'KY'),
	('Laos', 'LA'),
	('Lebanon', 'LE'),
	('Malaysia', 'MA'),
	('Mansi', 'MS'),
	('Mesopotamian', 'ME'),
	('Minyong', 'MY'),
	('Mongolia', 'MO'),
	('Monguor', 'MG'),
	('Myanmar', 'MM'),
	('Nanai', 'NA'),
	('Neghidhian', 'NG'),
	('Nepal', 'NE'),
	('Nganasan', 'NS'),
	('Oman', 'OM'),
	('Ostyak', 'OS'),
	('Pakistan', 'PK'),
	('Persian', 'PE'),
	('Philippines', 'PH'),
	('Phoenician', 'PO'),
	('Qatar', 'QA'),
	('Republic of Korea', 'RK'),
	('Republic of the Maldives', 'ML'),
	('Sanskrit', 'SA'),
	('Saudi Arabia', 'SB'),
	('Scythian', 'SC'),
	('Semitic', 'SE'),
	('Siberia', 'SI'),
	('Sri Lanka', 'SR'),
	('Sumerian', 'SU'),
	('Syria', 'SY'),
	('Taiwan', 'TW'),
	('Tajik', 'TJ'),
	('Tajikistan', 'TS'),
	('Tamil', 'TM'),
	('Thailand', 'TH'),
	('Tibet', 'TB'),
	('Timor-Leste', 'TL'),
	('Tungu', 'TN'),
	('Turkey', 'TU'),
	('Turkmenistan', 'TK'),
	('Tuva', 'TV'),
	('Ulci', 'UL'),
	('United Arab Emirates', 'UA'),
	('Urartu', 'UR'),
	('Uzbekistan', 'UZ'),
	('Vietnam', 'VT'),
	('Yakutian', 'YK'),
	('Yemen', 'YE'),
	('Albania', 'AL'),
	('Andorra', 'AN'),
	('Austria', 'AS'),
	('Bashkir', 'BS'),
	('Basque', 'BA'),
	('Belarus', 'BL'),
	('Belgium', 'BE'),
	('Bosnia-Herzegovina', 'BH'),
	('Bulgaria', 'BU'),
	('Byzantine', 'BZ'),
	('Caucasus', 'CC'),
	('Celtic', 'CE'),
	('Chuvash', 'CH'),
	('Croatia', 'CR'),
	('Cyprus', 'CY'),
	('Czechoslovakia', 'CZ'),
	('Czech Republic', 'CP'),
	('Denmark', 'DE'),
	('England', 'EN'),
	('Estonia', 'ES'),
	('Finland', 'FI'),
	('Flemish', 'FL'),
	('France', 'FR'),
	('Gaelic', 'GA'),
	('Gaul', 'GU'),
	('Germany', 'GE'),
	('Great Britain', 'GB'),
	('Greek', 'GR'),
	('Gypsy', 'GY'),
	('Hungary', 'HU'),
	('Iceland', 'IC'),
	('Ireland', 'IR'),
	('Italy', 'IT'),
	('Kalmyk', 'KL'),
	('Karelia', 'KA'),
	('Komi', 'KO'),
	('Lapp', 'LP'),
	('Latin', 'LA'),
	('Latvia', 'LV'),
	('Liechtenstein', 'LE'),
	('Lithuania', 'LI'),
	('Luxembourg', 'LU'),
	('Macedonian', 'MA'),
	('Malta', 'ML'),
	('Mari', 'MR'),
	('Moldova', 'MD'),
	('Montenegro', 'MN'),
	('Mordvinian', 'MO'),
	('Netherlands (Dutch)', 'DU'),
	('Norse', 'NS'),
	('Norway', 'NO'),
	('Oscan', 'OS'),
	('Ostrogoth', 'OG'),
	('Poland', 'PO'),
	('Portugal', 'PG'),
	('Roman', 'RM'),
	('Romania (Rumania)', 'RO'),
	('Russia', 'RU'),
	('San Marino', 'SM'),
	('Scandinavian', 'SD'),
	('Scotland', 'SC'),
	('Scythia', 'SY'),
	('Serbia', 'SE'),
	('Slavic', 'SL'),
	('Slovakia', 'SV'),
	('Slovenia', 'SI'),
	('Soviet', 'SO'),
	('Spain', 'SP'),
	('Sweden', 'SW'),
	('Switzerland', 'SZ'),
	('Tartar', 'TT'),
	('Teutonic', 'TU'),
	('Udmurtian', 'UD'),
	('Ukraine', 'UK'),
	('Wales', 'WA'),
	('Yugoslavia', 'YU'),
	('Acoma', 'AC'),
	('Aleutian', 'AU'),
	('Algonquin', 'AL'),
	('American', 'AM'),
	('Antigua and Barbuda', 'AN'),
	('Arikara', 'AR'),
	('Aruba', 'AB'),
	('Aztec', 'AZ'),
	('Bella Coola', 'BC'),
	('Blackfoot', 'BL'),
	('Canada', 'CA'),
	('Canada/Greenland', 'CG'),
	('Cherokee', 'CE'),
	('Cheyenne', 'CY'),
	('Chickasaw', 'CH'),
	('Chinook', 'CI'),
	('Choktaw', 'CO'),
	('Chumash', 'CU'),
	('Commonwealth of the Bahamas', 'BA'),
	('Creek', 'CR'),
	('Dakota', 'DA'),
	('Dominica', 'DO'),
	('Eskimo', 'ES'),
	('Eskimo (Greenland)', 'EK'),
	('Greenland', 'GL'),
	('Hopi', 'HO'),
	('Inuit', 'IN'),
	('Iroquois', 'IR'),
	('Jamaica', 'JM'),
	('Klamath', 'KL'),
	('Kwakiutl', 'KW'),
	('Lakota', 'LA'),
	('Mandan', 'MA'),
	('Mexico', 'ME'),
	('Navajo', 'NV'),
	('Ojibwe', 'OJ'),
	('Osage', 'OS'),
	('Pawnee', 'PW'),
	('Pequot', 'PE'),
	('Popoluca', 'PP'),
	('Potawatomi', 'PO'),
	('Pueblo', 'PU'),
	('Saint Kitts and Nevis', 'SK'),
	('Saint Vincent and the Grenadines', 'SV'),
	('Salish', 'SA'),
	('Seneca', 'SE'),
	('Shoshoni', 'SH'),
	('Sioux', 'SX'),
	('Tlingit', 'TL'),
	('United States', 'US'),
	('Yurok', 'YU'),
	('Zuni', 'ZU'),
	('Australia', 'AU'),
	('Caroline Is.', 'CI'),
	('Cook Islands', 'CO'),
	('Fiji', 'FJ'),
	('Guam', 'GM'),
	('Hawaii', 'HA'),
	('Kiribati', 'KI'),
	('Marquesas Islands', 'MA'),
	('Marshall Is.', 'MI'),
	('Melanesia', 'ME'),
	('Micronesia', 'MC'),
	('Nauru', 'NA'),
	('New Britain', 'NB'),
	('New Caledonia', 'NC'),
	('New Guinea', 'GU'),
	('New Zealand', 'NZ'),
	('Papua New Guinea', 'PN'),
	('Polynesia', 'PO'),
	('Republic of Palau', 'PA'),
	('Samoa', 'SA'),
	('Society Is.', 'SI'),
	('Solomon Islands', 'SO'),
	('Tonga', 'TO'),
	('Tuamotu', 'TU'),
	('Tuvalu', 'TV'),
	('Vanuatu', 'VA'),
	('Yolngu', 'YO'),
	('Araucanian', 'AC'),
	('Argentina', 'AR'),
	('Barbados', 'BB'),
	('Belize', 'BE'),
	('Bolivia', 'BO'),
	('Bororo', 'RR'),
	('Brazil', 'BR'),
	('Chile', 'CH'),
	('Chimalateco', 'CI'),
	('Colombia', 'CO'),
	('Costa Rica', 'CR'),
	('Cuba', 'CU'),
	('Dominican Republic', 'DR'),
	('Ecuador', 'EC'),
	('El Salvador', 'ES'),
	('Falkland Islands', 'FI'),
	('French Guiana', 'FG'),
	('Grenada', 'GR'),
	('Guatemala', 'GU'),
	('Guyana', 'GY'),
	('Haiti', 'HA'),
	('Honduras', 'HO'),
	('Inca', 'IN'),
	('Jamaica', 'JM'),
	('Mayan', 'MY'),
	('Nahuatl', 'NA'),
	('Netherlands (Dutch) Antilles', 'DA'),
	('Nicaragua', 'NI'),
	('Panama', 'PM'),
	('Paraguay', 'PA'),
	('Peru', 'PE'),
	('Puerto Rico', 'PR'),
	('Saint Lucia', 'SL'),
	('Suriname', 'SU'),
	('Trinidad and Tobago', 'TT'),
	('Uruguay', 'UR'),
	('Venezuela', 'VE'),
	('Virgin Islands', 'VI');